### ISSUE TITLE
Question: Do you get proper JSerrors through crashlytics with your logging setup?

### ISSUE THREAD

**Issue by Snorlock** [DanceDeets/dancedeets-react#1]
That meaning uncluthered JS, that they are sourcemapped? Or is this done in TrackJS?
Since we cant upload sourcemaps ot crashlytics, and ref the discussion:  https://github.com/mikelambert/react-native-fabric-crashlytics/issues/1
Where they are talking about doing on the client which is not preferred.

**Comment by mikelambert** [comment]
No, sourcemaps are not currently supported for react-native-fabric-crashlytics, and I do not get them in my project here.

Supposedly Sentry has React Native support that has automatic sourcemap support for iOS (and manual for Android), as seen here: https://docs.sentry.io/clients/react-native/ You may be interested in giving that a try? It's on my list to migrate myself, but not a high priority at the moment...

**Comment by Snorlock** [comment]
Yeah i started trying that out, I will see where it goes!
